version: '3'
services:
  registry:
    image: registry:2
    deploy:
      replicas: 1
    volumes:
      - "/media/DockerSlowShare/registry/data:/var/lib/registry"
    ports:
      - "5000:5000"
    networks:
      - registry

networks:
  registry:
