version: '3'
services:
  urbackup:
    image: uroni/urbackup-server
    deploy:
      replicas: 1
    volumes:
      - "/media/UrBackupStore/backups:/backups"
      - db-vol:/var/urbackup
    ports:
      - "55413-55415:55413-55415"
      - "35623:35623/udp"
    restart: unless-stopped
    network_mode: "bridge"

volumes:
  db-vol:
