version: '3'
services:
  portainer:
    ports:
      - "9000:9000"
    image: portainer/portainer
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/media/DockerFastShare/portainer/data:/data"
