version: "3"
services:

  redis:
    image: redis:3
    deploy:
      replicas: 1
    networks:
      - back

  rabbit:
    image: rabbitmq:3
    hostname: rabbit
    deploy:
      replicas: 1
    networks:
      - back

  celery:
    image: celery
    deploy:
      replicas: 1
    networks:
      - back

  events:
    image: registry.dezdez.com.au/taiga-events
    deploy:
      replicas: 1
    networks:
      - back

  taiga:
    image: registry.dezdez.com.au/taiga
    networks:
      - back
      - front
    deploy:
      replicas: 1
    ports:
      - "4000:80"
    environment:
      TAIGA_HOSTNAME: taiga.dezdez.com.au
      TAIGA_DB_HOST: 10.1.1.22
      TAIGA_DB_NAME: taigadb
      TAIGA_DB_USER: taiga
      TAIGA_DB_PASSWORD: password
      TAIGA_SSL_BY_REVERSE_PROXY: 'True'
      TAIGA_SLEEP: 60
    deploy:
      replicas: 1
    volumes:
      - "/media/DockerSlowShare/taiga/media:/usr/src/taiga-back/media"
      - "/media/DockerSlowShare/taiga/config:/taiga"

networks:
  back:
  front:
