version: '3'
services:
  torrentbox:
    image: linuxserver/transmission
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - "/media/Torrents:/downloads"
      - "/media/Torrents/config:/config"
      - "/media/Torrents/watch:/watch"
